### ISSUE TITLE
different between OrderOriginal and OrderPointer

### ISSUE THREAD

**Issue by podcastm1** [IT-SoC/Training#2]
https://github.com/IT-SoC/Training/blob/ca5499db6c194da96c3b8ff6b59fd15450602a3c/C/1MHz%20answer/1mhz.cpp#L53-L54

When you test the pointer parameters using with OrderPointer();
and Then you general test the no parameters using with OrderOriginal();

and include running time table (In my computing environment)

**Comment by Takayama-Lissajous** [comment]
1. Test OrderPointer function.
2. Test OrderOriginal function.
3. Compare elapsed time for each function test.

Is it Right?
 Thank you for your participation!

**Comment by Takayama-Lissajous** [comment]
Thank you for your participation.!

**Comment by podcastm1** [comment]
@Takayama-Lissajous yes compare elapsed time for each function test
